config/routes.rb
Predavanje8::Application.routes.draw do
  resources :courses
  resources :professors

end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :name, :prof_array
  has_and_belongs_to_many :professors
  def prof_array
    self.professor_ids.join(",")
  end
  def prof_array=(str)
    self.professor_ids= str.split(",")
  end
end

app/models/professor.rb
class Professor < ActiveRecord::Base
  attr_accessible :f_name, :l_name, :name
  has_and_belongs_to_many :courses
  def name
    "#{self.f_name} #{self.l_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  # GET /professors
  # GET /professors.json
  def index
    if params[:q]
      @professors = Professor.where("f_name like ?","%#{params[:q]}%")
    else
      @professors = Professor.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @professors, :methods => [:name] }
    end
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
    @professor = Professor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @professor }
    end
  end

  # GET /professors/new
  # GET /professors/new.json
  def new
    @professor = Professor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @professor }
    end
  end

  # GET /professors/1/edit
  def edit
    @professor = Professor.find(params[:id])
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(params[:professor])

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
        format.json { render json: @professor, status: :created, location: @professor }
      else
        format.html { render action: "new" }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /professors/1
  # PUT /professors/1.json
  def update
    @professor = Professor.find(params[:id])

    respond_to do |format|
      if @professor.update_attributes(params[:professor])
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor = Professor.find(params[:id])
    @professor.destroy

    respond_to do |format|
      format.html { redirect_to professors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" id="mojbox">
    <%= f.label :name, "Ime" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :prof_array, "Profesori na predmetu:" %><br />
    <%= f.text_field :prof_array, "data-pre" => @course.professors.to_json(:methods => [:name]) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @courses.each do |course| %>
  <tr>
    <td><%= course.name %></td>
    <td><%= link_to 'Show', course %></td>
    <td><%= link_to 'Edit', edit_course_path(course) %></td>
    <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @course.name %>
</p>


<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Predavanje8</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "token-input" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/professors/_form.html.erb
<%= form_for(@professor) do |f| %>
  <% if @professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
      <% @professor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :f_name, "Ime" %><br />
    <%= f.text_field :f_name %>
  </div>
  <div class="field">
    <%= f.label :l_name, "Prezime" %><br />
    <%= f.text_field :l_name %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/professors/edit.html.erb
<h1>Editing professor</h1>

<%= render 'form' %>

<%= link_to 'Show', @professor %> |
<%= link_to 'Back', professors_path %>

app/views/professors/index.html.erb
<h1>Listing professors</h1>

<table>
  <tr>
    <th>Ime</th>
    <th>Prezime</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @professors.each do |professor| %>
  <tr>
    <td><%= professor.f_name %></td>
    <td><%= professor.l_name %></td>
    <td><%= link_to 'Show', professor %></td>
    <td><%= link_to 'Edit', edit_professor_path(professor) %></td>
    <td><%= link_to 'Destroy', professor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Professor', new_professor_path %>

app/views/professors/new.html.erb
<h1>New professor</h1>

<%= render 'form' %>

<%= link_to 'Back', professors_path %>

app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_professor_path(@professor) %> |
<%= link_to 'Back', professors_path %>